### ISSUE TITLE
Can't capture intents broadcasted by Intent Wedge

### ISSUE THREAD

**Issue by rits-development** [datalogic/datalogic-android-sdk#3]
I'm trying to capture the intents broadcasted by the Intent Wedge which is enabled. 
However, my `BroadcastReceiver` isn't triggered.

I checked the general system LogCat output and noticed the following when I trigger a scan:
```
2019-09-11 18:08:18.429 2255-2342/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:966 android.content.ContextWrapper.sendBroadcast:437 com.datalogic.provider.IntentWedgeThread$1.handleMessage:97 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:164 
2019-09-11 18:08:18.431 749-2665/? E/ActivityManager: Sending non-protected broadcast com.datalogic.decodewedge.decode_action from system 2255:com.datalogic.service/1000 pkg com.datalogic.service
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19283)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19900)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:20042)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2971)
        at android.os.Binder.execTransact(Binder.java:706)
```

It seems as if Android is dismissing the intent because it's not protected which might explain why my `BroadcastReceiver` isn't being triggered.

Any idea?

Any help is highly appreciated!

## Extra system info
- device: Datalogic Memor 1
- SDK version: 1.17
- android version: 8.1.0
- compileSdkVersion: 27
- minSdkVersion: 16
- targetSdkVersion: 27

**Comment by mpennasilico** [comment]
Hi!

I suppose that your App is registering for receiving the Intent Wedge in the Manifest. Please, confirm it to have a complete understanding of the problem.

Anyway, Google introduced several limitations regarding Broadcast from Android 8, in order to improve dispatching performance. I strongly suggest to have a look here https://developer.android.com/about/versions/oreo/background#broadcasts. This could be very helpful to understand if your App is aligned to Android indications regarding this topic.

According to the Android documentation:
“_Android 8.0 (API level 26) makes these limitations more stringent.
- **Apps that target Android 8.0 or higher can no longer register broadcast receivers for implicit broadcasts in their manifest.** An implicit broadcast is a broadcast that does not target that app specifically. For example, ACTION_PACKAGE_REPLACED is an implicit broadcast, since it is sent to all registered listeners, letting them know that some package on the device was replaced. However, ACTION_MY_PACKAGE_REPLACED is not an implicit broadcast, since it is sent only to the app whose package was replaced, no matter how many other apps have registered listeners for that broadcast.
- Apps can continue to register for explicit broadcasts in their manifests.
- **Apps can use Context.registerReceiver() at runtime to register a receiver for any broadcast, whether implicit or explicit.**
- Broadcasts that require a signature permission are exempted from this restriction, since these broadcasts are only sent to apps that are signed with the same certificate, not to all the apps on the device._”

So, if your App registers itself for receiving the Intent Wedge in the Manifest, this approach works properly until Android 7. But instead, this feature will work as expected for all Android versions, If the App follows the new Google indication regarding the broadcast limitations, introduced by Android 8, that is to register the App to receive intents at runtime with the Context.registerReceiver() call.

Please, report us if this fixes your issue.

**Comment by laquint53** [comment]
Hi
I have the same issue...how did you solved it ??
Regards

**Comment by codybrookshear** [comment]
Hi @laquint53,
If you `"register the App to receive intents at runtime with the Context.registerReceiver() call", this should allow you to receive barcode data in an intent correctly.

Here are some sample apps that demonstrate calling `registerReceiver()`:

[DecodeIntent - Java](https://github.com/datalogic/android-samples-astudio/tree/master/Java/DecodeIntent)
[DecodeIntent - Kotlin](https://github.com/datalogic/android-samples-astudio/tree/master/Kotlin/DecodeIntent)

For example, here the line in the Java example where `registerReceiver()` is called:
https://github.com/datalogic/android-samples-astudio/blob/master/Java/DecodeIntent/app/src/main/java/com/datalogic/examples/decodeintent/IntentWedgeSample.java#L76

And as a best practice, unregisterReciver() should be called as well:
https://github.com/datalogic/android-samples-astudio/blob/master/Java/DecodeIntent/app/src/main/java/com/datalogic/examples/decodeintent/IntentWedgeSample.java#L85

**Comment by laquint53** [comment]
hi @codybrookshear
Thanks for the reply, for the oser manufacturer (zebra, bluebird...) the code bellow works, i use a ScanReceiver to receive barcode date in an intent.
For Datalogic it doesn't work...I prefer not use nugget package.

here my code :

private ScanReceiver _ScanReceiver;
private IntentFilter _ScanFilter;

 protected override void OnCreate(Bundle savedInstanceState)
{

_ScanReceiver = new ScanReceiver();
_ScanFilter = new IntentFilter("com.datalogic.decodewedge.decode_action")
_ScanFilter.AddCategory("com.datalogic.decodewedge.decode_category");
RegisterReceiver(_ScanReceiver, _ScanFilter);
}

 internal class ScanReceiver : BroadcastReceiver
    {
        public override void OnReceive(Context context, Intent intent)
        {
                if (intent?.Action == "com.datalogic.decodewedge.decode_category" //DataLogic
                {
                    codebarre = intent.GetStringExtra("com.datalogic.decode.intentwedge.barcode_string");                   
                    appService.OnScanReceived(this, codebarre, null, null);
                }

            }
}

**Comment by codybrookshear** [comment]
Ok, it's good to know you are doing Xamarin development. Even if you don't want to utilize our [NuGet package](https://www.nuget.org/packages/datalogic-xamarin-sdk/) ("Datalogic Xamarin SDK"), taking a look at our [DecodeIntent](https://datalogic.github.io/xamarin/samples) sample app could be useful.

This sample *only* uses the Datalogic Xamarin SDK to configure the IntentWedge feature based on [which of the 2 radio boxes are selected](https://github.com/datalogic/xamarin-samples/blob/master/DecodeIntent/DecodeIntent/IntentWedgeSample.cs#L167).

To avoid needing to use the Datalogic Xamarin SDK altogether, the IntentWedge settings could be configured ahead of time, for instance using the Settings app on the device (Settings > Datalogic Settings > Scanner Settings > Wedge > Intent wedge). **Intent wedge is diabled by default.** Other ways to configure this include using [OEMConfig](https://datalogic.github.io/oemconfig/scanner-settings#intent-wedge) via an EMM/MDM or using [Scan2Deploy Studio](https://datalogic.github.io/scan2deploy/studio/).

**Comment by TheKrushik** [comment]
I am use DecodeIntent - Kotlin Exemple

After that when I click "Start Service" or "Broadcast Intent" I get an error

```
2021-02-25 14:57:26.779 19956-19956/com.datalogic.examples.decodeintent E/com.datalogic.examples.decodeintent.IntentWedgeSample: Error in onCheckedChanged
    kotlin.KotlinNullPointerException
        at com.datalogic.examples.decodeintent.IntentWedgeSample$MyClickedItemListener.onCheckedChanged(IntentWedgeSample.kt:103)
        at android.widget.RadioGroup.setCheckedId(RadioGroup.java:190)
        at android.widget.RadioGroup.access$600(RadioGroup.java:57)
        at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:375)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:174)
        at android.widget.CompoundButton.toggle(CompoundButton.java:127)
        at android.widget.RadioButton.toggle(RadioButton.java:76)
        at android.widget.CompoundButton.performClick(CompoundButton.java:132)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


```

**Comment by tobiascapin** [comment]
I'm using this receiver in my activity:

```
ContextCompat.registerReceiver(activity, intentBroadcastReceiver, filter, null, handler, ContextCompat.RECEIVER_EXPORTED);


private BroadcastReceiver intentBroadcastReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
			//....
		}
}
```

but I still get the non-protected broadcast error while triggering a Memor 12 barcode scan:

```
ending non-protected broadcast com.myapp.ACTION from system 7218:com.datalogic.service/1000 pkg com.datalogic.service 
	java.lang.Throwable
		at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:13824)
		at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14546)
		at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13842)
		at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14720)
		at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2296)
		at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2658)
		at android.os.Binder.execTransactInternal(Binder.java:1280)
		at android.os.Binder.execTransact(Binder.java:1244)
```
